### ISSUE TITLE
Title Case or Localized title case?

### ISSUE THREAD

**Issue by tdd** [reactjs/fr.reactjs.org#18]
Hey @gaearon a typography question here!

React's docs use “reasonable title case” (pronouns, conjunctions, etc. are usually lowercase). This is not a de-facto English standard, but is commonplace in the press and has become widespread in English tech docs.

However, title casing is pretty foreign to other roman-letters languages, such as French.

Is this an intentional design choice that you wish roman-letters languages would preserve? Or was that a sort of reflex, and you don't mind locale-aware title casing?

French translations use the same casing as English so far, but it does feel foreign.

Let us know!

/cc @JeremiePat @shinework @tesseralis

**Comment by tesseralis** [comment]
@tdd I'd say do whatever looks normal in French.

**Comment by tdd** [comment]
@tesseralis awesome, I'll do an overhaul pass.

**Comment by tdd** [comment]
@reactjs/reactjs-org-french-translation attention à tous ! La politique de capitalisation des titres a changé, pour revenir à la casse française normale (seule la première lettre de la phrase est majuscule).

Je vais faire une PR dédiée pour les textes déjà fusionnés ou en passe de l'être. Faites juste attention lors de vos prochaines PR !
