### ISSUE TITLE
Git conflict syntax was not removed after before in docs/handling-events file

### ISSUE THREAD

**Issue by blade-sensei** [reactjs/fr.reactjs.org#242]
In the documentation you see <<<<< HEAD text.. and you have left the english original text and the ID of something

The error is founded exactly here 
https://github.com/reactjs/fr.reactjs.org/blob/master/content/docs/handling-events.md#-headlorsque-vous-utilisez-react-vous-navez-g%C3%A9n%C3%A9ralement-pas-besoin-dappeler-la-m%C3%A9thode-addeventlistener-pour-ajouter-des-%C3%A9couteurs-d%C3%A9v%C3%A9nements-event-listeners-ndt-%C3%A0-un-%C3%A9l%C3%A9ment-du-dom-apr%C3%A8s-que-celui-ci-est-cr%C3%A9%C3%A9-%C3%A0-la-place-on-fournit-l%C3%A9couteur-lors-du-rendu-initial-de-l%C3%A9l%C3%A9ment

**Comment by blade-sensei** [comment]
How can i contribute to fix this ?

**Comment by Nab69** [comment]
@blade-sensei  You can fix this with a pull request if you want, but it's a bug with a [commit](https://github.com/reactjs/fr.reactjs.org/commit/41d97a6bddbc146ff8e1eed94eea74d0366edbb4#diff-8ca12b03172ba3c2192ea86202f0823) from the bot and many pages have to be fixed.

**Comment by Nab69** [comment]
fixed #237
