### ISSUE TITLE
Ecriture inclusive => lecture pénible

### ISSUE THREAD

**Issue by Tilko** [reactjs/fr.reactjs.org#276]
Super doc ...
mais l'écriture inclusive est aussi pénible que le fait qu'il n'y ait qu'aussi peu de femme dans l'informatique.
Merci de ne pas combattre le feu par le feu.

**Comment by Nab69** [comment]
C'est en effet un choix éditorial, cependant hormis dans les premieres pages de la doc on rencontre assez peu l'écriture inclusive dans les explications. On va donc éviter de lancer un débat, je cloture donc. 😊

**Comment by Tilko** [comment]
Bon, j'aurai fait tout mon possible pour combattre ce fleau ... :)

**Comment by huitre** [comment]
Peut-on réouvrir ce problème ? Un frame n'est pas une tribune politique, et encore moins quand il s'agit de propagande communiste, merci.
