### ISSUE TITLE
Tutoriel

### ISSUE THREAD

**Issue by JeremiePat** [reactjs/fr.reactjs.org#3]
**Fichiers**
* [ ] `/content/tutorial/tutorial.md`
* [ ] `/content/tutorial/nav.yml`

**Recommandations**
Dans le menu on ne localise que les `title`. On ne touche pas aux ID ni aux URL.

Pour les exemples, on ne traduit que les commentaires et les éventuelles _string_ affichées mais **pas les noms de variables**.

**Comment by Chikimuras** [comment]
I'm in!

**Comment by JeremiePat** [comment]
Ok, je vais fermer cette issue. Comme l'a fait remarqué, @tdd, ce n'est pas très utile. Ce sera plus simple si tu créer directement une PR (même si elle n'est pas terminé ;)
