### ISSUE TITLE
🌍 Translation for faq-internals

### ISSUE THREAD

**Issue by sidbentifraouine** [reactjs/fr.reactjs.org#74]
Working on the translation for Virtual DOM and Internals 🙂

- id: faq-internals
- title: Virtual DOM and Internals
- permalink: docs/faq-internals.html
- layout: docs
- category: FAQ

**Comment by tdd** [comment]
Salut @sidbentifraouine,

Quand tu veux faire une trad, merci de suivre la procédure décrite dans #1 plutôt que d'ouvrir une *issue*. Ça te permettra notamment de garantir la consignation de ta « prise de main » et de recevoir tous nos conseils de première trad.

Je te cale ça là-bas et ferme cette issue.

**Comment by tdd** [comment]
@sidbentifraouine en fait je comprends pas trop ta prise de main, cette page est déjà prise (et la PR soumise) par @lbelavoir depuis un moment… Donc ne perds pas ton temps !

**Comment by sidbentifraouine** [comment]
Ah my bad 😅! je tâcherai de de ne pas refaire la même, merci @tdd
