### ISSUE TITLE
French translation final steps!

### ISSUE THREAD

**Issue by tesseralis** [reactjs/fr.reactjs.org#82]
Congrats! You all are almost done translating the React docs to French 🎉

A couple more things to do before we can mark this translation as complete:

* [x] Replace "reactjs.org" to "fr.reactjs.org" in the following places:
  * [x] package.json
  * [x] site-constants.js
  * [x] gatsby-config.js
  * [x] MarkdownPage (the link href in "Edit this page")
* [x] Change `html.js` to have the attribute `lang="fr"`
* [x] Go over each section in the site to:
  * [x] Make sure there are no formatting errors (dangling markdown/html tags) or untranslated English
  * [x] Make sure the sections and style are consistent.
* [x] Change the [DocSearch API key](https://github.com/reactjs/es.reactjs.org/blob/ed07fa53dc9ab7950e630900f7da3a7c821d63a6/src/components/LayoutHeader/DocSearch.js#L25). One of the maintainers needs to [sign up for DocSearch](https://community.algolia.com/docsearch/#join-docsearch-program)

**Comment by tdd** [comment]
DocSearch API key applied for, now waiting for their reply.

**Comment by tdd** [comment]
@tesseralis just pushed an updated DocSearch API key and index name, as per their instructions. I hope this is enough, and that they'll proactively index that thing! I only have access to analytics, not index info, in their UI.
